// generated by yarn generate:webp
import src600w from '~/assets/images/contact/hero@600w.webp';
import src960w from '~/assets/images/contact/hero@960w.webp';
import src1280w from '~/assets/images/contact/hero@1280w.webp';
import src1920w from '~/assets/images/contact/hero@1920w.webp';

const images = {
  src1920w,
  src600w,
  src960w,
  src1280w,
  aspectRatio: 5,
};

export default images;
